---
- name: BigBlueButton
  hosts: bbb
  become: yes
  vars_files:
    - vars.yml
  vars:
    nginx_ppa_use: yes
    nginx_ppa_version: stable
    bbb_letsencrypt_enable: yes
    bbb_letsencrypt_email: "{{ letsencrypt_email }}"
    bbb_coturn_enable: no
    bbb_turn_enable: yes
    bbb_stun_servers:
      - server: "turn-1.verschwoer.haus:443"
    bbb_turn_servers:
      - server: "turn-1.verschwoer.haus"
        port: "443"
        secret: "{{ turn_secret }}"
        tls: false
      - server: "turn-1.verschwoer.haus"
        port: "443"
        secret: "{{ turn_secret }}"
        tls: true
    bbb_greenlight_enable: no
    bbb_api_demos_enable: no
    bbb_disable_recordings: yes
    bbb_dialplan_quality: "cdquality"
    bbb_mute_on_start: no
    bbb_dialin_mask_caller: yes
    bbb_meteor:
      public:
        app:
          enableMultipleCameras: true
        kurento:
          cameraProfiles:
            - bitrate: 100
              default: false
              id: low
              name: Low
            - bitrate: 200
              default: true
              id: medium
              name: Medium
            - bitrate: 500
              default: false
              id: high
              name: High
            - bitrate: 800
              default: false
              id: hd
              name: High definition
            - bitrate: 1200
              default: false
              id: ultrahd
              name: Ultra High definition
          screenshare:
            constraints:
              video:
                frameRate:
                  ideal: 15
                  max: 30
    ufw_reset: no
    ufw_applications:
     - name: "Nginx Full"
     - name: "freeswitch"
  pre_tasks:
    - name: Ensure freeswitch ufw configuration is available
      copy:
        content: |
          [freeswitch]
          title=freeswitch
          description=freeswitch telecom stack
          ports=16384:32768/udp
        mode: 0644
        dest: /etc/ufw/applications.d/freeswitch
  roles:
    - geerlingguy.nginx
    - weareinteractive.ufw
    - n0emis.bigbluebutton
  tasks:
    - name: ensure http call to root is redirected
      copy:
        # FIXME: var
        content: |
          location = / {
            return 301 https://bbb.ulm.dev;
          }
        mode: 0755
        dest: /etc/bigbluebutton/nginx/redirectroot.nginx
      notify: reload nginx
    - name: FreeSWITCH dialplan muted-sound
      replace:
        path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
        after: '<profile name="{{ bbb_dialplan_quality }}">'
        before: '</profile>'
        regexp: '<param name="muted-sound" value=".*"/>'
        replace: '<!-- no muted-sound -->'
      notify:
      - restart bigbluebutton
