---
- name: BigBlueButton
  hosts: bbb
  become: yes
  vars_files:
    - vars.yml
  vars:
    nginx_ppa_use: yes
    nginx_ppa_version: stable
    bbb_letsencrypt_enable: yes
    bbb_letsencrypt_email: "{{ letsencrypt_email }}"
    bbb_coturn_enable: no
    bbb_turn_enable: yes
    bbb_stun_servers:
      - server: "turn-1.verschwoer.haus:443"
    bbb_turn_servers:
      - server: "turn-1.verschwoer.haus"
        port: "443"
        secret: "{{ turn_secret }}"
        tls: false
      - server: "turn-1.verschwoer.haus"
        port: "443"
        secret: "{{ turn_secret }}"
        tls: true
    bbb_greenlight_enable: no
    bbb_api_demos_enable: no
    bbb_disable_recordings: yes
    bbb_dialplan_quality: "cdquality"
    bbb_mute_on_start: no
    bbb_freeswitch_ipv6: true
    bbb_freeswitch_muted_sound: no
    bbb_dialin_mask_caller: yes
    bbb_dialin_footer: ""
    bbb_default_welcome_message_footer: ""
    bbb_allow_mods_to_eject_cameras: true
    bbb_learning_dashboard_enabled: false
    bbb_web_logouturl: "https://bbb.verschwoer.haus"
    _multikurento:
      videoMediaServer: mediasoup
      screenshareMediaServer: mediasoup
      audioMediaServer: mediasoup
      listenOnlyMediaServer: mediasoup
      localIpAddress: "{{ ansible_default_ipv4.address }}"
      mediasoup:
        webrtc:
          listenIps:
            - ip: "0.0.0.0"
              announcedIp: "{{ ansible_default_ipv4.address }}"
            - ip: "::"
              announcedIp: "{{ ansible_default_ipv6.address }}"
        plainRtp:
          listenIps:
            - ip: "0.0.0.0"
              announcedIp: "{{ ansible_default_ipv4.address }}"
            - ip: "::"
              announcedIp: "{{ ansible_default_ipv6.address }}"
    bbb_webrtc_sfu_multikurento: "{{ bbb_webrtc_sfu_multikurento_default | combine(_multikurento)  }}"
    bbb_meteor:
      public:
        note:
          url: "https://{{ inventory_hostname }}/pad"
        pads:
          url: "https://{{ inventory_hostname }}/pad"
        app:
          enableMultipleCameras: true
          mirrorOwnWebcam: true
        kurento:
          wsUrl: "wss://{{ inventory_hostname }}/bbb-webrtc-sfu"
          cameraSortingModes:
            defaultSorting: LOCAL_ALPHABETICAL
            paginationSorting: LOCAL_PRESENTER_ALPHABETICAL
    bbb_firewall_ufw:
      enabled: no # we're managing it ourselves:
    ufw_reset: no
    ufw_applications:
     - name: "Nginx Full"
     - name: "freeswitch"
  pre_tasks:
    - name: Ensure freeswitch ufw configuration is available
      copy:
        content: |
          [freeswitch]
          title=freeswitch
          description=freeswitch telecom stack
          ports=16384:32768/udp
        mode: 0644
        dest: /etc/ufw/applications.d/freeswitch
  roles:
    - geerlingguy.nginx
    - weareinteractive.ufw
    - ebbba.bigbluebutton
  tasks:
    - name: ensure http call to root is redirected
      copy:
        # FIXME: var
        content: |
          location = / {
            return 301 https://bbb.verschwoer.haus;
          }
        mode: 0755
        dest: /etc/bigbluebutton/nginx/redirectroot.nginx
      notify: reload nginx
