---
roles:
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: geerlingguy.nginx
    version: 2.8.0
  - name: ebbba.bigbluebutton
    version: 'v2.5.1-1'
  - name: weareinteractive.ufw
    version: 1.10.0
  - name: geerlingguy.redis
    version: 1.7.0
  - name: geerlingguy.postgresql
    version: 2.2.0
  - name: geerlingguy.ruby
    version: 2.6.0
  - name: geerlingguy.certbot
    version: 3.1.0
