---
- name: Ensure git and pip are available
  apt:
    name:
    - git
    - python3-pip
    state: present

- name: Create system user for bbb-exporter
  user:
    name: bbb-exporter
    shell: /bin/bash
    home: /var/lib/bbb-exporter
    create_home: yes
    password: '!'
    update_password: on_create
    system: yes
    state: present

- name: Ensure /var/www/bbb-exporter exists
  file:
    path: /var/www/bbb-exporter
    state: directory
    mode: '0755'
    owner: bbb-exporter
    group: bbb-exporter

- name: Checkout bbb-exporter
  git:
    repo: https://github.com/greenstatic/bigbluebutton-exporter.git
    dest: /var/www/bbb-exporter
    version: "{{ bbb_exporter_version }}"
  become: yes
  become_user: bbb-exporter

- name: Ensure bbb-exporter is owner of /var/www/bbb-exporter
  file:
    path: /var/www/bbb-exporter
    recurse: yes
    owner: bbb-exporter
    group: bbb-exporter

- name: Ensure required pip packages are installed
  pip:
    requirements: /var/www/bbb-exporter/requirements.txt
    state: present
    extra_args: --user
  become: yes
  become_user: bbb-exporter

- name: Ensure environment for bbb-exporter
  template:
    src: env.j2
    dest: /var/www/bbb-exporter/.env
    owner: bbb-exporter

- name: Ensure systemd unit for bbb-exporter
  template:
    src: bbb-exporter.service
    dest: /etc/systemd/system/bbb-exporter.service

- name: Enable bbb-exporter
  systemd:
    daemon_reload: yes
    name: bbb-exporter
    enabled: yes
    state: started

- name: Ensure exporter config for ufw
  copy:
    content: |
      [bbb-exporter]
      title=bbb-exporter
      description=prometheus bbb exporter
      ports=9688/tcp
    mode: 0644
    dest: /etc/ufw/applications.d/bbb-exporter
